sportwatch/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('timk/', include('timk.urls'))
]

timk/urls.py
from django.urls import path
from . import views
from .views import AllListView,MatchListView, MatchDetailView, GroupDetailView, TeamListView


app_name = 'timk'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', AllListView.as_view(), name='world-cup-groups'),
    path('sports/', views.sports_list, name='sports'),
    path('games/', MatchListView.as_view(), name='world-cup-groups'),
    path('teams/', TeamListView.as_view(), name='teams'),
    path('group-<str>-matches/', GroupDetailView.as_view(), name='group-matches'),
    path('<slug:slug>/', MatchDetailView.as_view(), name='match-details'),
    
]

watsport/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

timk/models.py
import datetime
from django.db import models
from django.utils import timezone
from autoslug import AutoSlugField
#from django_countries.fields import CountryField
from .utils import getcountry


countr_l = getcountry()


class Sport(models.Model):
    name = models.CharField(max_length=100, unique=True)
    #duration = models.TimeField(default='')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Event(models.Model):
    name = models.CharField(blank=False, max_length=50)
    sport = models.ForeignKey(Sport, on_delete=models.SET_NULL, null=True, to_field='name')
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Venue(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


group_choice = (('A', 'A'), ('B', 'B'),('C', 'C'),('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'))


class Team(models.Model):
    #group_choice = (('A', 'A'), ('B', 'B'),('C', 'C'),('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'))
    gender_choice = (('F', 'Female'), ('M', 'Male'), ('N', 'No Gender'))
    name = models.CharField(blank=False, max_length=50)
    group = models.CharField(choices=group_choice, max_length=1, blank=True, null=True)
    sport = models.ForeignKey(Sport, on_delete=models.SET_NULL, blank=True, null=True)
    country = models.CharField(choices=countr_l, max_length=50)
    country_code = models.CharField(max_length=6, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=gender_choice)
    website = models.URLField()
    image = models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.country_code != self.country:
            self.country_code = self.country
        super(Team, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']    


class Channel(models.Model):
    name = models.CharField(blank=False, max_length=50)
    country = models.CharField(blank=True, max_length=50)
    language = models.CharField(blank=False, max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name


def get_populate_from(instance):
        return '%s-%s-%s' % (instance.date, instance.team1, instance.team2)


class Game(models.Model):
    
    sport = models.ForeignKey(Sport,  on_delete=models.SET_NULL, null=True)
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, null=True)
    venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True)
    date = models.DateField()
    time = models.TimeField()
    team1 = models.ForeignKey(Team, related_name='team1', on_delete=models.SET_NULL, null=True)
    team2 = models.ForeignKey(Team, related_name='team2', on_delete=models.SET_NULL, null=True)
    slug = AutoSlugField(populate_from=get_populate_from, unique=True, editable=False)
    #group = models.CharField(choices=group_choice, default=group_choice[0][0], max_length=1)
    channels = models.ManyToManyField(Channel)
    

    def __str__(self):
        return '%s-%s' % (self.team1, self.team2)

    class Meta:
        ordering = ['date','time']

timk/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.template.loader import get_template
from django.utils import timezone
from django.http import HttpResponse, Http404
from .models import  Event, Sport, Team, Channel, Game, Venue
import datetime

# Create your views here.

class AllListView(generic.ListView):
    model = Game

    #queryset = Team.objects.order_by('name')
    #context_object_name = 'team_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()

        result_team = Team.objects.values('group').distinct().order_by('group')
        context['grl'] = result_team

        team_list = Team.objects.order_by('name')
        context['teaml'] = team_list

        result_date = Game.objects.values('date').distinct().order_by('date')
        context['datelist'] = result_date

        return context

class MatchListView(generic.ListView):
    model = Game
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        result_team = Team.objects.values('group').distinct().order_by('group')
        context['grl'] = result_team
        return context


class GroupDetailView(generic.ListView):
    model = Game
    template_name = 'timk/group-view.html'
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        if self.kwargs['str']:
            group_str = self.kwargs['str']
        #teams_group = Team.filter(group=group_str)
        context['test'] = Game.objects.all().filter(team1__group__icontains=group_str).distinct()
        return context


class TeamListView(generic.ListView):
    model = Team
    queryset = Team.objects.order_by('name')
    context_object_name = 'team_list'
    
    # def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
    #    context['grouplist'] = Team.objects.all().order_by('group')
    #    return context


class MatchDetailView(generic.DetailView):
    model = Game
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)       
        return context
    

def index(request):
    return render(request, 'timk/index.html', {})

def detail(request, event):
    event = get_object_or_404(Event, name=event)
    return render(request, 'timk/details.html', {'event': event})

'''def detail(request, competition_id):
    display = "You're looking at competition %s."
    return HttpResponse(display % competition_id)'''

def team(request, team_id):
    return HttpResponse("teams list")

def events(request):
    return HttpResponse(render(request, 'base.html'))

def current_datetime(request):
    now = datetime.datetime.now()
    t = get_template('current_datetime.html')
    html = t.render({'current_date': now})
    return HttpResponse(html)

def sports_list(request):
    #sports = Sport.objects
    #return render(request, 'sports.html', {'sports':sports})
    return render(request, 'sports.html')

timk/templates/competitions.html
<html><body><div>
    <h1><a href="/">SportWatch Blog</a></h1>
</div>

{% for comp in Competition %}
    <div>
        <h1><a href="">{{ comp.name }}</a></h1>
        //\\##<p>{{ comp.name|linebreaksbr }}</p>
    </div>
{% endfor %}
</body>
</html>

timk/templates/index.html
{% if competition_list %}
    <ul>
    {% for competition in competition_list %}
        <li><a href="/{{ competition.name }}/">{{ competion.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No competitions are available.</p>
{% endif %}

timk/templates/schedule.html
<html>
<head>
    <title>Ordering notice</title>
</head>
<body>
    <h1>Schedules view</h1>
    <p>Here are the items you've ordered:</p>
</body>
</html>

timk/templates/sports.html
<html><body><div>
    <h1><a href="/">Django Girls Blog</a></h1>
</div>

{% for sport in Sports %}
    <div>
        <h1><a href="">{{ sport.name }}</a></h1>
        //\\##<p>{{ sport.text|linebreaksbr }}</p>
    </div>
{% endfor %}
</body>
</html>

timk/templates/timk/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Russia 2018 FIFA World Cup Football Games{% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container-fluid">
                <h1>My First Bootstrap Page</h1>
    <div id="sidebar">
        {% include 'timk/navbar.html' %}
    </div>
    <div class="row">
            <div class="col-sm-4">.col-sm-4</div>
            <div class="col-sm-8">.col-sm-8</div>
          </div> 
    <div id="content">
        {% block content %}
        <p>Wait for the content {{now}}</p>
        {% endblock content %}
    </div>
    </div>
</body>
</html>

timk/templates/timk/details.html
<h1>{{ event }}</h1>
<ul>

    <li><a href= {{ event.website }}>{{ event.website }}</a></li>

</ul>

timk/templates/timk/game_detail.html
{% extends "timk/base.html" %}

{% block content %}


<h1>{{ object }}  and {{ object.slug }}</h1>
<p>{{ object.time }} {{ object.date }}</p>
<p>Stadium: {{ object.venue }}</p>
<p>Channels: {{object.channels}}</p>
<p>Test: {{test}}</p>
<p>Testkw: {{testkw}}</p>
<p>Date: {{ now|date }}</p>

{%endblock content %}

timk/templates/timk/game_list.html
{% extends "timk/index.html" %}

{% block content %}

<!-- Page Heading --> 
{% if not grl %}
      <h1 class="my-4">Great games coming soon. Stay tuned.
        <small></small>
      </h1>
{% else %}
      <h1 class="my-4">Great games coming soon. Check the groups.
        <small></small>
      </h1>
 {% for gr in grl %}
 {% if forloop.first %}<div class="row">{% endif %}
 <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item z-depth-5 box-shadow">
    <div class="cardo h-100 z-depth-5">
      <a href="{% url 'timk:group-matches' gr.group %}"><div class="card-header bg-dark text-white">          <h4 class="card-title">Group {{gr.group}}</h4>
        </div></a>
      
      <div class="card-body">
        <p class="card-text">
            {% for game in object_list %}
            {% if game.team1.group == gr.group %}
            <p class="card-text"><a href="{% url 'timk:match-details' game.slug %}">{{ game.team1 }} - {{ game.team2 }}</a>
            {{game.date|date:"D d M Y"}} at {{game.time}}</p> 
            
          {% endif %}
          {% endfor %}
      </div>
    </div>
  </div>
  {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
      {% if forloop.last %}</div>{% endif %}
 

{% endfor %} 

{% endif %}
{% endblock content %}

timk/templates/timk/group-view.html
{% extends "timk/base.html" %}

 {% block content %}
 <p>Groups Schedule {{now}}</p>
 <p>{{test}}</p>
{% for match in test %}
    <p>{{match.team1}} - {{match.team2}} on {{match.date}} at {{match.venue}} </p>
</br><p>{% for chan in match.channels %}
    {{chan}}</p>
    {% endfor %}

{% endfor %}
 {% endblock content %}

timk/templates/timk/index.html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>2018 FIFA Men's World Cup Russia</title>

  <script type="application/ld+json">
    {% for game in object_list %}
    {
      "@context":"http://schema.org",
      "@type":"BroadcastEvent",
      "name": "2018 FIFA Men's World Cup Russia",
      "description": "{{ game.team1 }} vs. {{ game.team2 }}",
      "isLiveBroadcast": "http://schema.org/True",
      "startDate": "{{ game.date|date:"Y-m-d" }}T{{ game.time|time:"H:i" }}",
      "URL":"http://localhost:8000/timk/",
      "broadcastOfEvent": {
        "@type": "SportsEvent",
        "name": "2018 FIFA Men's World Cup Russia",
        "description": "{{ game.team1 }} vs. {{ game.team2 }}",
        "competitor": [
          {
            "@type": "SportsTeam",
            "name": "{{ game.team1 }}"
          },
          {
            "@type": "SportsTeam",
            "name": "{{ game.team2 }}"
          }
        ],
        "startDate": "{{ game.date|date:"Y-m-d" }}T{{ game.time|time:"H:i" }}",
        "Duration":"01:45:00",
        "location" : {
          "@type" : "Place",
          "name" : "{{ game.venue }}",
          "address" : {
            "@type" : "PostalAddress",
             "addressLocality" : "{{ game.venue.city }}",
             "addressCountry" : "RU"
             }
         }
      }
    }
    {% endfor %}


    </script>

  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="/static/timk/css/awzom.css" rel=stylesheet type="text/css">
  <link href="/static/timk/css/flags.css" rel=stylesheet type="text/css">
  <link href="/static/timk/assets/docs.css" rel="stylesheet" type="text/css">
  <link href="/static/timk/css/flag-icon.css" rel="stylesheet" type="text/css">


</head>

<body>
  <div class="w3-top">
    <div class="w3-bar w3-large topnav">
      <div class- "w3-cell">
        <div class="w3-wide w3-xxlarge w3-container w3-display-left sitetitle">
          <b>
            <strong>WatSport</strong>
          </b>
        </div>
        <div class="w3-display-right">
          <a href="#group_list" class="w3-bar-item w3-button w3-hide-small">Groups</a>
          <a href="#team_list" class="w3-bar-item w3-button w3-hide-small">Teams</a>
          <a href="#footer" class="w3-bar-item w3-button w3-hide-small">About</a>
        </div>
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="myFunction()">&#9776;</a>
      </div>

      <div class="w3-bar-block w3-red w3-hide w3-hide-large w3-hide-medium">
        <a href="#group_list" class="w3-bar-item w3-button">Link 1</a>
        <a href="#team_list" class="w3-bar-item w3-button">Link 2</a>
        <a href="#" class="w3-bar-item w3-button">Link 3</a>
      </div>
    </div>
  </div>

  <div class="w3-container" style="padding-top:60px;">
    <div class="w3-row-padding w3-center">

      <div class="w3-col m9 w3-centre">

        <div class="w3-row">
          <div class="w3-col m4 w3-centre">
            <div class="w3-card-4 w3-green w3-mobile" style="width:96%">
              <p>{% now "jS F Y H:i" %} </p>
            </div>
          </div>
          <div class="w3-col m4">
            <div class="w3-card-4 w3-green w3-mobile" style="width:96%">
              {% with startdate="2018-06-14" %}
              <p>Starting on {{ startdate }}</p>
              {% endwith %}
            </div>
          </div>
          <div class="w3-col m4">
            <div class="w3-card-4 w3-green w3-mobile" style="width:96%">
              <p>Live your passion</p>
            </div>
          </div>

        </div>

        <div>
          {% for gr in grl %} {% if forloop.first %}
          <div>
            <div class="w3-row">{% endif %}

              <div class="w3-col m6 l3">

                <div class="w3-card w3-mobile w3-center" style="width:96%">
                  <a href="{% url 'timk:group-matches' gr.group %}">
                    <header class="w3-container w3-light-blue">
                      <p>
                        <strong>Group {{gr.group}}</strong>
                      </p>
                    </header>
                  </a>
                  <div>
                    {% for game in object_list %} {% if game.team1.group == gr.group %}
                    <div>
                      <p style="font-size:12px;">
                        <strong style="font-weight:700;">{{ game.team1 }} - {{ game.team2 }}</strong>
                        <br> {{game.date|date:"D d M Y"}} at {{game.time}}</div>
                    <hr style="width:80%;margin:-4px;"></hr>{% if forloop.last %}{% endif %} {% endif %} {% endfor %} </p>
                  </div>
                </div>

              </div>
              {% if forloop.last %}
            </div>
          </div>
          {% endif %}{% endfor %}

        </div>
      </div>

      <div class="w3-col m3 w3-pink w3-center w3-hide-small" style="height:400px;position:sticky;top:90px;"></div>
      <div class="w3-col m3 w3-pink w3-center w3-hide-medium" style="height:400px;"></div>


      <div id="group_list">
        <div id="team_list" class="w3-col m9 w3-center" style="padding-top: 25px">



          {% for team in teaml %} {% if forloop.first %}
          <table class="w3-table w3-light-grey" style="padding-top:30px;font-size:12px;">
            {% endif %}

            <tr>
              <td>
                <span class="flag-icon flag-icon-{{ team.country|lower }}" title="{{ team.country|lower }}"></span>
              </td>
              <td>{{ team }}</td>
              <td>Gr. {{team.group}}</td>
              <td>
                <a href="{{team.website}}" target="_blank">Web</a>
              </td>

            </tr>

            {% if forloop.last %}
          </table>

          {% endif %} {% empty %} The list is on it is way. Stay tuned. {% endfor %}
        </div>
      </div>

      <div id="game_details">
        <div class="w3-col m9 w3-center" style="padding-top:25px;font-size:12px;">


          
          {% for game in object_list %}
        <div class="w3-container">
          <div class="w3-card w3-light-gray">
          <h1 id=#{{ game.slug }}><span class="flag-icon flag-icon-background flag-icon-{{ game.team1.country|lower }}" style="height:60%"></span> {{ game.team1 }} - {{ game.team2 }}
            <span class="flag-icon flag-icon-{{ game.team2.country|lower }}" title="{{ game.team2.name }}" style="height:60%"></span></h1>
          
          <p> {{ game.date }} {{ game.time }}</p>
          <p>Stadium: {{ game.venue }} City: {{ game.venue.city }}</p>
          <p>Channels: {% for channel in game.channels.all %}
            <a href="{{channel.website}}" target="_blank">{{ channel }} </a> {% endfor %}</p>
          </div>
        </div>
          {% endfor %}



        </div>
      </div>

    </div>


  </div>
  </div>




  </div>
  <footer id="footer" class="footer"><p>Copyright &copy; WatSport 2018</p></footer>

  <script>
    function myFunction() {
      var x = document.getElementById("demo");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }
  </script>
</body>

</html>

timk/templates/timk/index1.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>2018 FIFA World Cup Russia</title>

    <link href="/static/timk/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" type="text/css">
    <!-- Custom styles for this template -->
    <link href="/static/timk/css/4-col-portfolio.css" rel="stylesheet" type="text/css">
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.css" rel="stylesheet"> -->
    <link href="/static/timk/css/flags.css" rel=stylesheet type="text/css">
    <link href="/static/timk/assets/docs.css" rel="stylesheet" type="text/css">
    <link href="/static/timk/css/flag-icon.css" rel="stylesheet" type="text/css">

  </head>

  <body class="bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'timk:world-cup-groups' %}">WatSports</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'timk:world-cup-groups' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'timk:teams' %}">Teams</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'timk:world-cup-groups' %}">Games</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
      <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
        
        
          <!-- Page Heading 
      <h1 class="my-4">Page Heading
        <small>Secondary Text</small>
      </h1>-->

      

          {% block content %}  
          {% endblock content %}
      </div>
      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <!-- /.row -->
    </div></div></div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; WatSports 2018</p>      </div>
      <!-- /.container -->
    </footer>


  </body>

</html>

timk/templates/timk/index2.html
{% extends "timk/base.html" %}

{% block title %}Russia 2018 FIFA World Cup Football Games{% endblock title %}

timk/templates/timk/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <!-- Brand -->
        <a class="navbar-brand" href="#">Navbar</a>
      
        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="{% url 'timk:world-cup-groups' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'timk:teams' %}">Teams</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'timk:world-cup-groups' %}">Games</a></li>
        <li>{{now}}</li>
    </ul>
    </div>
</nav>

timk/templates/timk/team_list.html
{% extends 'timk/index.html' %}
{% block content %}



{% for team in team_list %}
{% if forloop.first %}
    <div class="row"><div style="padding-left:40px;width:100%;background: rgba(76, 175, 80, 0.8) "><h4 style="font-weight:bold">2018 FIFA World Cup Russia Teams</h4>
      <div class="row"> {% endif %}
      
        <div style="width: 50%; display:inline-block;font-weight: 500;">
              <div style="width:11%;display:inline-block;border:1px grey;vertical-align:middle">
                <div class="flag-wrapper">
                  <div class="flag flag-icon-background flag-icon-{{ team.country|lower }}" title="{{ team.country|lower }}">
          </div></div></div>
          <div  style="display: inline-block;vertical-align: baseline;width:25%"><p class="text-justify">{{ team }}</p>
          </div>
          <div style="display: inline-block;width:15%">gr. {{team.group}}</div>
          <div style="display:inline-block"><a href="{{team.website}}" target="_blank">
            <span class="badge badge-info">www</span>
      <span class="sr-only">www</span></a></div></div>
    
      {% if forloop.counter|divisibleby:2 %}</div><div class="row">{% endif %}
          {% if forloop.last %}</div></div>{% endif %}
    

  {% empty %} The list is on it is way. Stay tuned.


{% endfor %}
</br>

  {% endblock %}